---
# tasks file for ansible-role-kubernetes-create-cluster

- name: Test for existing K8s cluster
  ansible.builtin.command: ls /etc/kubernetes/
  register: dirtest
  changed_when: false
  tags:
    - kubeconfig
    - kubeadm

# EXAMPLE: If you need to set any config for kubeadm startup
# - name: Build kubeadm-config.yaml file
#   ansible.builtin.blockinfile:
#     path: /tmp/kubeadm-config.yaml
#     block: |
#       kind: ClusterConfiguration
#       apiVersion: kubeadm.k8s.io/v1beta3
#       ---
#       kind: KubeletConfiguration
#       apiVersion: kubelet.config.k8s.io/v1beta1
#       cgroupDriver: systemd
#     create: yes
#   tags:
#     - kubeadm

# - name: Kubeadm init
#   ansible.builtin.shell: kubeadm init --config /tmp/kubeadm-config.yaml
#   register: rslt
#   when: "'admin.conf' not in dirtest.stdout"
#   tags: kubeconfig

- name: Kubeadm init
  ansible.builtin.command: kubeadm init
  register: rslt
  when: "'admin.conf' not in dirtest.stdout"
  tags: kubeconfig

- name: Store init output
  ansible.builtin.copy:
    content: "{{ rslt.stdout }}"
    dest: "/etc/kubernetes/kubeadm-init.stdout"
    mode: '644'
  when: "'admin.conf' not in dirtest.stdout"
  tags: kubeconfig

- name: Ensure .kube directory exists.
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '644'

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link

- name: Copy kubeconfig to local machine (root user)
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/{{ inventory_hostname }}-config
    flat: true
  when: local_user == "root"
  tags:
    - cpkubeconfig

- name: Copy kubeconfig to local machine (non root user)
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/{{ inventory_hostname }}-config
    flat: true
  when: local_user != "root"
  tags: cpkubeconfig

# Install Calico, cause Weave seems to have gone busted as of Nov 13th 2021
- name: Test for existing Calico install
  ansible.builtin.shell:
    cmd: kubectl get crd | grep -o calico -m 1
  register: calico_crd
  failed_when: calico_crd.rc > 1
  changed_when: false
  tags: calico

# URLs and install have changed in 2023
- name: Download and apply the Calico CNI manifest
  ansible.builtin.command:
    kubectl apply -f "{{ calico_url }}"
  when: "'calico' not in calico_crd.stdout"
  tags: calico
